/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'tools' : IDL.Null,
  'entertainment' : IDL.Null,
  'productivity' : IDL.Null,
  'education' : IDL.Null,
  'games' : IDL.Null,
});
export const AppId = IDL.Nat;
export const App = IDL.Record({
  'id' : AppId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'downloadCount' : IDL.Nat,
  'rating' : IDL.Float64,
  'price' : IDL.Opt(IDL.Float64),
  'iconUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addApp' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Opt(IDL.Float64),
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [AppId],
      [],
    ),
  'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'getAppById' : IDL.Func([AppId], [App], ['query']),
  'getAppsByCategory' : IDL.Func([Category], [IDL.Vec(App)], ['query']),
  'seedSampleApps' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'tools' : IDL.Null,
    'entertainment' : IDL.Null,
    'productivity' : IDL.Null,
    'education' : IDL.Null,
    'games' : IDL.Null,
  });
  const AppId = IDL.Nat;
  const App = IDL.Record({
    'id' : AppId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'downloadCount' : IDL.Nat,
    'rating' : IDL.Float64,
    'price' : IDL.Opt(IDL.Float64),
    'iconUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addApp' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Opt(IDL.Float64),
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [AppId],
        [],
      ),
    'getAllApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'getAppById' : IDL.Func([AppId], [App], ['query']),
    'getAppsByCategory' : IDL.Func([Category], [IDL.Vec(App)], ['query']),
    'seedSampleApps' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };